### ISSUE TITLE
[bug]ipv6没有监听

### ISSUE THREAD

**Issue by logce** [oneclickvirt/incus_images#1]
模板 alpine_3.18_3.18_x86_64_cloud.zip
sshd_config中
ListenAddress 0.0.0.0
ListenAddress 0.0.0.0
应该是
ListenAddress 0.0.0.0
ListenAddress ::
其他模版不清楚

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/incus_images/commit/446e94a14795cd7dfef5c19a1e2258f4065b06a9

fixed
